import PDFDocument from "pdfkit";
import type { Visitor, User } from "../types/index.js";

export function generateSecurityReportPDF(
  visitors: Visitor[],
  period: string,
  type: "weekly" | "monthly",
  users: Map<number, User>
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.rect(0, 0, doc.page.width, 100).fill("#1A1A2E");
    doc.fillColor("#EAB308").fontSize(28).text("HENSEK", 50, 30, { align: "left" });
    doc.fillColor("#FFFFFF").fontSize(14).text("Company Management System", 50, 62);
    doc.moveDown(3);

    // Title
    doc.fillColor("#1C1917").fontSize(20).text(`Security ${type === "weekly" ? "Weekly" : "Monthly"} Report`, { align: "center" });
    doc.fontSize(12).fillColor("#6B7280").text(`Period: ${period}`, { align: "center" });
    doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, { align: "center" });
    doc.moveDown(2);

    // Summary box
    doc.rect(50, doc.y, doc.page.width - 100, 60).fill("#FEFCE8").stroke("#EAB308");
    const summaryY = doc.y - 55;
    doc.fillColor("#1C1917").fontSize(12).text(`Total Visitors: ${visitors.length}`, 70, summaryY + 10);
    const activeNow = visitors.filter(v => !v.timeOut).length;
    doc.text(`Currently On-Site: ${activeNow}`, 70, summaryY + 28);
    const withCars = visitors.filter(v => v.plateNumber).length;
    doc.text(`Visitors with Vehicles: ${withCars}`, 250, summaryY + 10);
    doc.moveDown(2);

    // Visitors table header
    doc.fillColor("#1A1A2E").rect(50, doc.y, doc.page.width - 100, 24).fill();
    const tableY = doc.y - 20;
    doc.fillColor("#FFFFFF").fontSize(10);
    doc.text("Name", 60, tableY + 7);
    doc.text("Phone", 175, tableY + 7);
    doc.text("Destination", 280, tableY + 7);
    doc.text("Time In", 375, tableY + 7);
    doc.text("Time Out", 455, tableY + 7);
    doc.moveDown(0.5);

    // Visitor rows
    visitors.forEach((v, i) => {
      if (doc.y > 720) { doc.addPage(); }
      const rowY = doc.y;
      if (i % 2 === 0) doc.rect(50, rowY, doc.page.width - 100, 18).fill("#F9FAFB");
      doc.fillColor("#1C1917").fontSize(9);
      doc.text(v.name.substring(0, 18), 60, rowY + 4);
      doc.text(v.phone || "—", 175, rowY + 4);
      doc.text(v.officeDestination.substring(0, 18), 280, rowY + 4);
      doc.text(new Date(v.timeIn).toLocaleTimeString(), 375, rowY + 4);
      doc.text(v.timeOut ? new Date(v.timeOut).toLocaleTimeString() : "On-Site", 455, rowY + 4);
      doc.moveDown(0.4);
    });

    if (visitors.length === 0) {
      doc.fillColor("#6B7280").fontSize(11).text("No visitors recorded for this period.", { align: "center" });
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(9).fillColor("#9CA3AF").text(
      `This report was automatically generated by the Hensek Security System.`,
      { align: "center" }
    );

    doc.end();
  });
}

export function generateSafetyReportPDF(
  data: {
    period: string;
    type: "weekly" | "monthly";
    staffOnDuty: User[];
    duties: Array<{ siteName: string; date: string; shiftStart: string; shiftEnd: string; taskDescription: string; staffName: string; status: string }>;
    sites: Array<{ name: string; address?: string }>;
  }
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.rect(0, 0, doc.page.width, 100).fill("#1A1A2E");
    doc.fillColor("#EAB308").fontSize(28).text("HENSEK", 50, 30);
    doc.fillColor("#FFFFFF").fontSize(14).text("Company Management System", 50, 62);
    doc.moveDown(3);

    doc.fillColor("#1C1917").fontSize(20).text(`Safety ${data.type === "weekly" ? "Weekly" : "Monthly"} Report`, { align: "center" });
    doc.fontSize(12).fillColor("#6B7280").text(`Period: ${data.period}`, { align: "center" });
    doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, { align: "center" });
    doc.moveDown(2);

    // Summary
    doc.rect(50, doc.y, doc.page.width - 100, 60).fill("#FEFCE8").stroke("#EAB308");
    const sy = doc.y - 55;
    doc.fillColor("#1C1917").fontSize(12);
    doc.text(`Staff On Duty: ${data.staffOnDuty.length}`, 70, sy + 10);
    doc.text(`Active Sites: ${data.sites.length}`, 70, sy + 28);
    doc.text(`Total Duty Records: ${data.duties.length}`, 280, sy + 10);
    doc.moveDown(2);

    // Duties table
    if (data.duties.length > 0) {
      doc.fillColor("#1A1A2E").fontSize(14).text("Duty Assignments", 50);
      doc.moveDown(0.5);
      doc.rect(50, doc.y, doc.page.width - 100, 24).fill("#1A1A2E");
      const th = doc.y - 20;
      doc.fillColor("#FFFFFF").fontSize(9);
      doc.text("Staff", 60, th + 7);
      doc.text("Site", 155, th + 7);
      doc.text("Date", 255, th + 7);
      doc.text("Shift", 325, th + 7);
      doc.text("Status", 430, th + 7);
      doc.moveDown(0.5);

      data.duties.forEach((d, i) => {
        if (doc.y > 720) doc.addPage();
        const ry = doc.y;
        if (i % 2 === 0) doc.rect(50, ry, doc.page.width - 100, 18).fill("#F9FAFB");
        doc.fillColor("#1C1917").fontSize(8);
        doc.text(d.staffName.substring(0, 16), 60, ry + 4);
        doc.text(d.siteName.substring(0, 16), 155, ry + 4);
        doc.text(d.date, 255, ry + 4);
        doc.text(`${d.shiftStart}-${d.shiftEnd}`, 325, ry + 4);
        doc.text(d.status, 430, ry + 4);
        doc.moveDown(0.4);
      });
    }

    doc.moveDown(2);
    doc.fontSize(9).fillColor("#9CA3AF").text("This report was automatically generated by the Hensek Safety System.", { align: "center" });
    doc.end();
  });
}
